;; claude-guard built-in command declarations.
;;
;; A declaration tells the elaborator which options a program takes and
;; which of them take a value, so a pattern's `-...` swallows `-C .` as
;; one option and `-fxd` splits into its flags. It also says where a
;; program carries another command, so a rule about `sed` holds for
;; `sudo sed ...`, `ssh nas 'sed ...'`, and `bash -c 'sed ...'` alike.
;;
;;   (command name
;;     (option "-C" :value)           ; one value, attached or the next word
;;     (option "-P" "--no-pager")     ; a bare flag, short and long forms
;;     (option "--color" :optional)   ; a value only when attached: --color=always
;;     (subcommand stash :alias save (option "-q" "--quiet"))
;;     :inner (command)               ; the arguments are a command
;;     :inner (command :from 1)       ; after the first positional (timeout 5s cmd)
;;     :inner (script :from 1)        ; the positionals from 1 on are a script (ssh)
;;     :inner (script :from 0 :when "-c") ; positional 0 is a script under -c (bash)
;;     :inner (script :option "-c"))  ; the value of -c is a script (nu, python3)
;;
;; Only the programs that carry other commands ship here. Everything else
;; comes from `claude-guard commands add <name>`, which asks carapace and
;; writes ~/.config/claude-guard/commands/<name>.scm. Option lists below
;; were taken from `carapace <name> export` on 2026-09-06, except sh and
;; python3, which carapace has no flags for.

(command sudo
  (option "-A" "--askpass")
  (option "-b" "--background")
  (option "-B" "--bell")
  (option "-C" "--close-from" :value)
  (option "-e" "--edit")
  (option "-g" "--group" :value)
  (option "-h" "--help")
  (option "--host" :value)
  (option "-l" "--list")
  (option "-i" "--login")
  (option "-n" "--non-interactive")
  (option "-U" "--other-user" :value)
  (option "-E" "--preserve-env" :optional)
  (option "-P" "--preserve-groups")
  (option "-p" "--prompt" :value)
  (option "-K" "--remove-timestamp")
  (option "-k" "--reset-timestamp")
  (option "-H" "--set-home")
  (option "-s" "--shell")
  (option "-S" "--stdin")
  (option "-u" "--user" :value)
  (option "-v" "--validate")
  (option "-V" "--version")
  :inner (command))

(command env
  (option "--block-signal" :optional)
  (option "-C" "--chdir" :value)
  (option "-v" "--debug")
  (option "--default-signal" :optional)
  (option "--help")
  (option "-i" "--ignore-environment")
  (option "--ignore-signal" :optional)
  (option "--list-signal-handling")
  (option "-0" "--null")
  (option "-S" "--split-string" :value)
  (option "-u" "--unset" :value)
  (option "--version")
  :inner (command))

(command nice
  (option "-n" "--adjustment" :value)
  (option "--help")
  (option "--version")
  :inner (command))

(command nohup
  (option "--help")
  (option "--version")
  :inner (command))

(command timeout
  (option "-f" "--foreground")
  (option "--help")
  (option "-k" "--kill-after" :value)
  (option "-p" "--preserve-status")
  (option "-s" "--signal" :value)
  (option "-v" "--verbose")
  (option "--version")
  :inner (command :from 1))

(command xargs
  (option "-E" :value)
  (option "-I" :value)
  (option "-a" "--arg-file" :value)
  (option "-d" "--delimiter" :value)
  (option "-e" "--eof" :optional)
  (option "-x" "--exit")
  (option "--help")
  (option "-p" "--interactive")
  (option "-l" :value)
  (option "-n" "--max-args" :value)
  (option "-s" "--max-chars" :value)
  (option "-L" "--max-lines" :value)
  (option "-P" "--max-procs" :value)
  (option "-r" "--no-run-if-empty")
  (option "-0" "--null")
  (option "-o" "--open-tty")
  (option "--process-slot-var" :value)
  (option "-i" "--replace" :optional)
  (option "--show-limits")
  (option "-t" "--verbose")
  (option "--version")
  :inner (command))

(command ssh
  (option "-4")
  (option "-6")
  (option "-A")
  (option "-B" :value)
  (option "-C")
  (option "-D" :value)
  (option "-E" :value)
  (option "-F" :value)
  (option "-G")
  (option "-I" :value)
  (option "-J" :value)
  (option "-K")
  (option "-L" :value)
  (option "-M")
  (option "-N")
  (option "-O" :value)
  (option "-Q" :value)
  (option "-R" :value)
  (option "-S" :value)
  (option "-T")
  (option "-V")
  (option "-W" :value)
  (option "-X")
  (option "-Y")
  (option "-a")
  (option "-b" :value)
  (option "-c" :value)
  (option "-e" :value)
  (option "-f")
  (option "-g")
  (option "-i" :value)
  (option "-k")
  (option "-l" :value)
  (option "-m" :value)
  (option "-n")
  (option "-o" :value)
  (option "-p" :value)
  (option "-q")
  (option "-s")
  (option "-t")
  (option "-v")
  (option "-w" :value)
  (option "-x")
  (option "-y")
  :inner (script :from 1))

(command bash
  (option "-c")
  (option "-e")
  (option "-u")
  (option "-x")
  (option "-o" :value)
  (option "--debugger")
  (option "--dump-po-strings")
  (option "-D" "--dump-strings")
  (option "-i")
  (option "--init-file" :value)
  (option "-l" "--login")
  (option "--noediting")
  (option "--noprofile")
  (option "--norc")
  (option "--posix")
  (option "-r")
  (option "--rcfile" :value)
  (option "--restricted")
  (option "-s")
  (option "-v" "--verbose")
  (option "--version")
  :inner (script :from 0 :when "-c"))

(command sh
  (option "-c")
  (option "-e")
  (option "-u")
  (option "-x")
  (option "-i")
  (option "-l")
  (option "-s")
  (option "-o" :value)
  :inner (script :from 0 :when "-c"))

(command nu
  (option "-c" "--commands" :value)
  (option "--config" :value)
  (option "--env-config" :value)
  (option "-e" "--execute" :value)
  (option "-h" "--help")
  (option "--ide-ast")
  (option "--ide-check" :value)
  (option "--ide-complete" :value)
  (option "--ide-goto-def" :value)
  (option "--ide-hover" :value)
  (option "-I" "--include-path" :value)
  (option "-i" "--interactive")
  (option "--log-level" :value)
  (option "--log-target" :value)
  (option "-l" "--login")
  (option "-n" "--no-config-file")
  (option "--no-std-lib")
  (option "--plugin-config" :value)
  (option "--stdin")
  (option "-m" "--table-mode" :value)
  (option "--testbin" :value)
  (option "-t" "--threads" :value)
  (option "-v" "--version")
  :inner (script :option "-c"))

(command python3
  (option "-c" :value)
  (option "-m" :value)
  (option "-W" :value)
  (option "-X" :value)
  (option "-B")
  (option "-E")
  (option "-I")
  (option "-O")
  (option "-q")
  (option "-s")
  (option "-S")
  (option "-u")
  (option "-v")
  (option "-x")
  :inner (script :option "-c"))
